###
@baseUrl = http://localhost:5052/api
@token_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc0ZTM0YjA4LWU0NDMtNGY1ZC1iN2EwLTMzODQwN2EzYzhkMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NzY2MDA4MzUsImlzcyI6IlBldEFkb3B0QVBJIiwiYXVkIjoiUGV0QWRvcHRDbGllbnQifQ.cMEthcytgaqHeZ2fP1f63f7x9FhORD2TTGWUWPL-F3c
@token_shelter = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjcyMzU2NDlkLWFlOTQtNDZkMC05NzUxLThiZWNiNjc3OGJjZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im93bmVyZWVzYTlAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWhtZWQgb21lciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBldE93bmVyIiwiZXhwIjoxNzc2NjAwOTM5LCJpc3MiOiJQZXRBZG9wdEFQSSIsImF1ZCI6IlBldEFkb3B0Q2xpZW50In0.vZPNna8i_BvlP-CyiIcIGgx80q12NsCbrE4umIyU3_s
@token_adopter = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjExYWMzOGM1LWNlOTQtNDk2MC04YWY1LTUwMWZlMDE1MWZkMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Ik1va2FAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQkxBQkxBIEFkb3B0ZXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG9wdGVyIiwiZXhwIjoxNzc2NjAyNTU0LCJpc3MiOiJQZXRBZG9wdEFQSSIsImF1ZCI6IlBldEFkb3B0Q2xpZW50In0.UWkOLmUo_P70uBl8azqokka60-rlDTkrZRON8IZ2h0s

###############################################
# 1. AUTH
###############################################
### Register Shelter
# @name registerShelter
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Happy Paws Shelter",
  "email": "PetOwnerrr@test.com",
  "password": "Test@1234",
  "role": "PetOwner"
}

###

### Register PetOwner
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "ahmed omer",
  "email": "ownereesa9@test.com",
  "password": "Test@1234",
  "role": "PetOwner"
}

###

### Register Adopter
# @name registerAdopter
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "BLABLA Adopter",
  "email": "Moka@test.com",
  "password": "Test@1234",
  "role": "Adopter"
}

###

### Login as Admin
# @name loginAdmin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Admin@1234"
}

###

### Login as Shelter
# @name loginShelter
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ownereesa9@test.com",
  "password": "Test@1234"
}

###

### Login as Adopter
# @name loginAdopter
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "adopter@test.com",
  "password": "Test@1234"
}


###############################################
# 2. ADMIN — Users Management
###############################################

### Get All Pending Users
GET {{baseUrl}}/admin/pending-users
Authorization: Bearer {{token_admin}}

###

### Approve Shelter Account
PUT {{baseUrl}}/admin/approve-user/7235649d-ae94-46d0-9751-8becb6778bcf
Authorization: Bearer {{token_admin}}

###

### Reject User Account
PUT {{baseUrl}}/admin/reject-user/f5c205cd-0d39-4584-80e0-d7f4b9f4e65a
Authorization: Bearer {{token_admin}}


###############################################
# 3. PETS — Public (No Login)
###############################################

### Get All Approved Pets
GET {{baseUrl}}/pets

###

### Get Pet By Id
GET {{baseUrl}}/pets/24


###

### Search Pets — All Filters
GET {{baseUrl}}/pets/search?animalType=Dog&breed=Husky&maxAge=24&location=Cairo

###

### Search Pets — Only Animal Type
GET {{baseUrl}}/pets/search?animalType=cat

###

### Search Pets — Only Location
GET {{baseUrl}}/pets/search?location=Alex&breed=Husky


### Search Pets — Only Age
GET {{baseUrl}}/pets/search?maxAge=5&location=Cairo


###############################################
# 4. PETS — Owner (Shelter/PetOwner)
###############################################

### Get My Pets
GET {{baseUrl}}/pets/my-pets
Authorization: Bearer {{token_shelter}}

###

### Create New Pet
# @name createPet
POST {{baseUrl}}/pets
Authorization: Bearer {{token_shelter}}
Content-Type: application/json

{
  "name": "Hamada",
  "animalType": "Dog",
  "breed": "Bla Husky",
  "age": 10,
  "gender": "Female",
  "healthStatus": "Vaccinated and healthy",
  "description": "Very friendly and playful dog, looking for a loving home",
  "location": "cairo",
  "ImageUrls": ["https://example.com/dog1.jpg", "https://example.com/dog2.jpg"  ]
}

###

### Update Pet
PUT {{baseUrl}}/pets/1
Authorization: Bearer {{token_shelter}}
Content-Type: application/json

{
  "name": "Buddy Updated",
  "location": "Giza"
}

###

### Delete Pet (Soft Delete)
DELETE {{baseUrl}}/pets/8
Authorization: Bearer {{token_shelter}}


###############################################
# 5. ADMIN — Pets Management
###############################################

### Get All Pending Approval Pets
GET {{baseUrl}}/admin/pending-pets
Authorization: Bearer {{token_admin}}

###

### Approve Pet
PUT {{baseUrl}}/admin/approve-pet/4
Authorization: Bearer {{token_admin}}

###

### Reject Pet
PUT {{baseUrl}}/admin/reject-pet/26
Authorization: Bearer {{token_admin}}


###############################################
# 6. ADOPTER HISTORY
###############################################

### Add History
POST {{baseUrl}}/adopterhistory
Authorization: Bearer {{token_adopter}}
Content-Type: application/json

{
  "previousPetName": "Max",
  "previousPetType": "dog",
  "veterinaryReference": "Dr. Ahmed - 01012345678",
  "experience": "I had a dog for 3 years and took great care of him",
  "yearOfAdoption": 2022
}

###

### Get My Histories
GET {{baseUrl}}/adopterhistory
Authorization: Bearer {{token_adopter}}

###

### Delete History
DELETE {{baseUrl}}/adopterhistory/1
Authorization: Bearer {{token_adopter}}


###############################################
# 7. ADOPTION REQUESTS
###############################################

### Submit Adoption Request
POST {{baseUrl}}/adoption/request
Authorization: Bearer {{token_adopter}}
Content-Type: application/json

{
  "petId": 1,
  "message": "I love this pet and I have experience with dogs"
}

###

### Get My Requests (Adopter)
GET {{baseUrl}}/adoption/my-requests
Authorization: Bearer {{token_adopter}}

###

### Get Requests By Pet (Owner)
GET {{baseUrl}}/adoption/pet/1/requests
Authorization: Bearer {{token_shelter}}

###

### Accept Request (Owner)
PUT {{baseUrl}}/adoption/request/13/accept
Authorization: Bearer {{token_shelter}}

###

### Reject Request (Owner)
PUT {{baseUrl}}/adoption/request/13/reject
Authorization: Bearer {{token_shelter}}


###############################################
# 8. FAVORITES
###############################################

### Add Pet to Favorites by Pet Id
POST {{baseUrl}}/favorites/24
Authorization: Bearer {{token_adopter}}

###

### Get My Favorites 
GET {{baseUrl}}/favorites
Authorization: Bearer {{token_adopter}}

###

### Remove from Favorites by Pet Id
DELETE {{baseUrl}}/favorites/23
Authorization: Bearer {{token_adopter}}


###############################################
# 9. REVIEWS
###############################################

### Create Review
POST {{baseUrl}}/reviews
Authorization: Bearer {{token_adopter}}
Content-Type: application/json

{
  "petId": 1,
  "rating": 5,
  "comment": "Amazing experience! The shelter was very helpful"
}

###

### Get Owner Reviews (Public)
GET {{baseUrl}}/reviews/owner/bc4bbdb8-0e02-48c4-b05b-41bc3225ebbd?page=2&pageSize=2


###
GET {{baseUrl}}/pets?page=2&pageSize=10
###
### Get My notifications 
GET {{baseUrl}}/notifications
Authorization: Bearer {{token_adopter}}
### Get My notifications 
GET {{baseUrl}}/notifications
Authorization: Bearer {{token_shelter}}
### Get My notifications
GET {{baseUrl}}/notifications
Authorization: Bearer {{token_admin}}